youtube_trends_platform:
  target: spark
  outputs:
    spark:
      type: spark
      method: thrift
      host: spark_thriftserver
      port: 10001
      catalog: youtube_trends
      schema: silver
      threads: 10
      auth: NOSASL

    trino:
      type: trino
      host: trino
      port: 8080
      user: dbt
      catalog: pg_bi_db
      schema: gold
      threads: 2

    postgres:
      type: postgres
      host: pg_bi_db
      port: 5432
      user: admin
      password: admin
      dbname: bi
      schema: bi
      threads: 2