version: 2

models:
  - name: videos_enriched
    description: >
      Gold-level enriched fact table combining video snapshots, engagement metrics,
      growth deltas, descriptive metadata, language normalization, and geographic context.
      Designed for analytics and visualization (Grafana, BI tools).

    columns:
      - name: video_id
        description: Unique identifier of the YouTube video

      - name: region_id
        description: Region code where the video was trending

      - name: language_id
        description: Normalized language identifier (ISO-based)

      - name: language_id_src
        description: Raw language code as received from the YouTube API

      - name: channel_id
        description: Unique identifier of the channel that published the video

      - name: category_id
        description: YouTube category identifier of the video

      - name: video_snapshot_at
        description: Timestamp when the video metrics snapshot was collected

      - name: video_published_at
        description: Original publication timestamp of the video

      - name: view_count
        description: Total number of views at the snapshot time

      - name: like_count
        description: Total number of likes at the snapshot time

      - name: favorite_count
        description: Total number of favorites at the snapshot time

      - name: comment_count
        description: Total number of comments at the snapshot time

      - name: view_growth
        description: Increase in views compared to the previous snapshot for the same video and region

      - name: like_growth
        description: Increase in likes compared to the previous snapshot for the same video and region

      - name: favorite_growth
        description: Increase in favorites compared to the previous snapshot for the same video and region

      - name: comment_growth
        description: Increase in comments compared to the previous snapshot for the same video and region

      - name: title
        description: Title of the video

      - name: description
        description: Description text of the video

      - name: duration
        description: Duration of the video in ISO 8601 format

      - name: channel_title
        description: Human-readable name of the channel

      - name: category_name
        description: Human-readable name of the video category

      - name: language_name
        description: >
          Resolved human-readable language name derived from normalized language data
          or fallback mapping based on source language code

      - name: region_name
        description: Human-readable region name

      - name: latitude
        description: Latitude of the region (used for geographic visualizations)

      - name: longitude
        description: Longitude of the region (used for geographic visualizations)