version: 2

models:

  - name: videos_enriched
    description: >
      Gold-level enriched fact table for YouTube videos.
      Combines snapshot-level engagement metrics and growth
      with descriptive attributes from all dimension tables.
      Each row represents a video in a specific region at a specific snapshot time.

    columns:

      # ============================
      # KEYS
      # ============================

      - name: video_id
        description: Unique YouTube video identifier
        tests:
          - not_null

      - name: region_id
        description: Region (country) identifier
        tests:
          - not_null

      - name: language_id
        description: Language identifier of the video

      - name: channel_id
        description: Channel identifier owning the video

      - name: category_id
        description: Category identifier of the video

      # ============================
      # TIME
      # ============================

      - name: snapshot_at
        description: Timestamp representing when the metrics snapshot was taken
        tests:
          - not_null

      - name: snapshot_date
        description: Date (derived from snapshot_at) used for aggregation

      - name: video_published_at
        description: Date when the video was originally published

      # ============================
      # METRICS (ABSOLUTE)
      # ============================

      - name: view_count
        description: Total view count at snapshot time

      - name: like_count
        description: Total like count at snapshot time

      - name: favorite_count
        description: Total favorite count at snapshot time

      - name: comment_count
        description: Total comment count at snapshot time

      # ============================
      # METRICS (GROWTH)
      # ============================

      - name: view_growth
        description: Change in view count since previous snapshot for the same video and region

      - name: like_growth
        description: Change in like count since previous snapshot for the same video and region

      - name: favorite_growth
        description: Change in favorite count since previous snapshot for the same video and region

      - name: comment_growth
        description: Change in comment count since previous snapshot for the same video and region

      # ============================
      # VIDEO ATTRIBUTES
      # ============================

      - name: title
        description: Video title

      - name: description
        description: Video description

      - name: duration
        description: Video duration in ISO-8601 format

      # ============================
      # DIMENSION ATTRIBUTES
      # ============================

      - name: channel_title
        description: Display name of the YouTube channel

      - name: category_name
        description: Human-readable video category name

      - name: language_name
        description: Human-readable language name

      - name: region_name
        description: Human-readable region name