version: 2

models:

  # =========================
  # DIMENSIONS
  # =========================

  - name: dim_categories
    description: "YouTube video categories reference table."
    columns:
      - name: category_id
        description: "Unique identifier of the YouTube category."
        tests:
          - not_null
          - unique
      - name: category_name
        description: "Human-readable category name."
      - name: created_at
        description: "Timestamp when the category was created in the source."

  - name: dim_channels
    description: "Latest known channel metadata derived from videos."
    columns:
      - name: channel_id
        description: "Unique identifier of the YouTube channel."
        tests:
          - not_null
          - unique
      - name: channel_title
        description: "Channel display name."
      - name: updated_at
        description: "Most recent timestamp the channel appeared in the source data."

  - name: dim_languages
    description: "Languages reference table."
    columns:
      - name: language_id
        description: "ISO language identifier."
        tests:
          - not_null
      - name: language_name
        description: "Human-readable language name."
      - name: created_at
        description: "Timestamp when the language was created in the source."

  - name: dim_regions
    description: "YouTube regions reference table."
    columns:
      - name: region_id
        description: "ISO country/region code."
        tests:
          - not_null
          - unique
      - name: region_name
        description: "Human-readable region name."
      - name: created_at
        description: "Timestamp when the region was created in the source."

  - name: dim_videos
    description: "Video-level attributes that do not change frequently."
    columns:
      - name: video_id
        description: "Unique YouTube video identifier."
        tests:
          - not_null
      - name: title
        description: "Video title."
      - name: description
        description: "Video description."
      - name: duration
        description: "Video duration in ISO-8601 format."
      - name: published_at
        description: "Timestamp when the video was published."
      - name: category_id
        description: "Category ID associated with the video."
      - name: channel_id
        description: "Channel ID that published the video."

  # =========================
  # FACT TABLES
  # =========================

  - name: fct_videos
    description: "Snapshot fact table containing absolute engagement metrics per video and region."
    columns:
      - name: video_id
        description: "Unique YouTube video identifier."
        tests:
          - not_null
      - name: region_id
        description: "Region where the metrics were collected."
        tests:
          - not_null
      - name: language_id
        description: "Normalized language identifier."
      - name: language_id_src
        description: "Raw language identifier from the API."
      - name: channel_id
        description: "Channel ID that published the video."
      - name: category_id
        description: "Category ID associated with the video."
      - name: published_at
        description: "Timestamp when the video was published."
      - name: snapshot_at
        description: "Timestamp when the metrics snapshot was taken."
        tests:
          - not_null
      - name: view_count
        description: "Total number of views at snapshot time."
      - name: like_count
        description: "Total number of likes at snapshot time."
      - name: favorite_count
        description: "Total number of favorites at snapshot time."
      - name: comment_count
        description: "Total number of comments at snapshot time."

  - name: fct_videos_growth
    description: "Derived fact table computing growth metrics between snapshots."
    columns:
      - name: video_id
        description: "Unique YouTube video identifier."
        tests:
          - not_null
      - name: region_id
        description: "Region where the metrics were collected."
        tests:
          - not_null
      - name: language_id
        description: "Normalized language identifier."
      - name: language_id_src
        description: "Raw language identifier from the API."
      - name: channel_id
        description: "Channel ID that published the video."
      - name: category_id
        description: "Category ID associated with the video."
      - name: published_at
        description: "Timestamp when the video was published."
      - name: snapshot_at
        description: "Timestamp of the snapshot."
        tests:
          - not_null
      - name: view_count
        description: "Total views at snapshot time."
      - name: like_count
        description: "Total likes at snapshot time."
      - name: favorite_count
        description: "Total favorites at snapshot time."
      - name: comment_count
        description: "Total comments at snapshot time."
      - name: view_growth
        description: "Delta in views compared to the previous snapshot."
      - name: like_growth
        description: "Delta in likes compared to the previous snapshot."
      - name: favorite_growth
        description: "Delta in favorites compared to the previous snapshot."
      - name: comment_growth
        description: "Delta in comments compared to the previous snapshot."